spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: jhona_mysql
    url: jdbc:mysql://localhost:3306/prueba_springboot
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
